Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import numpy as np
cm_bm = LinearSegmentedColormap.from_list("mycmapbm", ["#ffa1cf","#f37726","#a0c3ff"])
colors = np.array(["#ffa1cf", "#f37726", "#a0c3ff"])
color_array = colors[y].tolist()  # Map each row to its corresponding color


scatter_matrix(df, c =color_array, figsize=(10,10),  # c : color acording to classes
               hist_kwds={'color':'blue','bins':20, 'alpha':0.5}, alpha=1.)
# Legend
handles = [mpatches.Patch(color=colors[i], label=iris.target_names[i]) for i in range(len(class_names))]
plt.legend(handles=handles, bbox_to_anchor=(1.05, 1), loc='upper left')

plt.show()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 13>[0;34m()[0m
[1;32m     10[0m scatter_matrix(df, c [38;5;241m=[39mcolor_array, figsize[38;5;241m=[39m([38;5;241m10[39m,[38;5;241m10[39m),  [38;5;66;03m# c : color acording to classes[39;00m
[1;32m     11[0m                hist_kwds[38;5;241m=[39m{[38;5;124m'[39m[38;5;124mcolor[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124mblue[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mbins[39m[38;5;124m'[39m:[38;5;241m20[39m, [38;5;124m'[39m[38;5;124malpha[39m[38;5;124m'[39m:[38;5;241m0.5[39m}, alpha[38;5;241m=[39m[38;5;241m1.[39m)
[1;32m     12[0m [38;5;66;03m# Legend[39;00m
[0;32m---> 13[0m handles [38;5;241m=[39m [mpatches[38;5;241m.[39mPatch(color[38;5;241m=[39mcolors[i], label[38;5;241m=[39miris[38;5;241m.[39mtarget_names[i]) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m([43mclass_names[49m))]
[1;32m     14[0m plt[38;5;241m.[39mlegend(handles[38;5;241m=[39mhandles, bbox_to_anchor[38;5;241m=[39m([38;5;241m1.05[39m, [38;5;241m1[39m), loc[38;5;241m=[39m[38;5;124m'[39m[38;5;124mupper left[39m[38;5;124m'[39m)
[1;32m     16[0m plt[38;5;241m.[39mshow()

[0;31mNameError[0m: name 'class_names' is not defined
NameError: name 'class_names' is not defined

