Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/homebrew/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
P_1 = np.array([0,1,1,0,0,1])
P1_ = np.array([1,1,1,1,1,0,0,1,0,0,0,1,0,1])
P_2 = np.array([1,0,0,1,1,1])
P2_ = np.array([1,0,0,0,0,1,0,1,1,1,1,0,1,0])
P1 = np.outer(P_1,P1_)
P2 = 2*np.outer(P_2,P2_)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m P_1 [38;5;241m=[39m [43mnp[49m[38;5;241m.[39marray([[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m1[39m])
[1;32m      2[0m P1_ [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m1[39m])
[1;32m      3[0m P_2 [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m1[39m,[38;5;241m0[39m,[38;5;241m0[39m,[38;5;241m1[39m,[38;5;241m1[39m,[38;5;241m1[39m])

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

